version: '3.8'
services:
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/d/Docker/dbtool_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: test
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10

  nginx:
    image: paulgwebster/nginx:1.21.5-23012022
    volumes:
    - .etc/templates:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=paulwebster.org
    - NGINX_PORT=80

volumes:
  pgadmin: